name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      - name: Install Dependencies
        run: go install

      - name: Build
        run: go build

      - name: Run unit tests with coverage
        run: bash unit-test-coverage.sh
      - name: Run integration tests
        run: go test -v -tags=integration ./...
      - name: Run smoke tests
        run: go test -v -tags=smoke ./smoke/...